language: python
dist: xenial
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coverage
  - pip install .

script:
  - coverage run setup.py test

after_success:
  - pip install coveralls && coveralls
  - pip install codecov && codecov
